---
title: "Week 3 Discussion File"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Part A: Make edits (no conflict)

```{r partner_1a}
# Partner 1: 
# Run the code below to see the original graph
# Change the code below to make the point color change based on 'cut', and update the theme to theme_bw(). Update the title to include your first name. 

ggplot(data = diamonds, aes(x = carat, y = price)) +
  geom_point(aes(color = cut)) +
  theme_bw() +
  labs(title = "GAVI was here")
```

```{r partner_2a}
# Partner 2: 
# Run the code below to see the original graph
# Change the code below to make the geom a geom_jitter, and update the theme to theme_light. Update the title to include your first name. 

ggplot(data = diamonds, aes(x = color, y = carat)) +
  geom_jitter(aes(color = clarity)) +
  theme_light() +
  labs(title = "Indigo was here")

```

## PART B: Make problems

```{r break-it-1}
ggplot(data = diamonds, aes(x = depth, y = carat)) +
  geom_point(color = "pink") +
  theme_void() + 
  labs(title = "WRECK IT UP!!!!!!!!!!!")

MATH_IS_COOL <- 45 + 1

### Kept both graphs since they so cool - IB

ggplot(data = diamonds, aes(x = depth, y = carat)) +
  geom_point() +
  theme_void() + 
  geom_text(label = "HEYYY")

# how u like my graph??

```

```{r break-it-2}



# Obviously keep this sick function
# function

fx_cool <- function(name){
  print(paste(name, "is cool", sep = " "))
}

fx_cool("Indigo")

ggplot(data = diamonds, aes(x = depth, y = carat)) +
  geom_point(color = "pink") +
  theme_void() + 
  labs(title = "WRECK IT UP!!!!!!!!!!!") + 
  geom_text(label="Look at this!", 
    x=4.1,
    y=20,
    label.padding = unit(0.55, "lines"), # Rectangle size around label
    label.size = 0.35,
    color = "black",
    fill="#69b3a2")

#I STOLE THE LABEL CODE FROM THE WEB!!! sorry r-graph-gallery

#### Hows life? I miss you friend!
# Awwwww it's weird you know but it's good!!! Miss you !


100+1

# = Dalmatians


```

## END Discussion 3
